"""Comprehensive Nifty universe + sector groupings + ETF list."""

NIFTY_50 = [
    "RELIANCE.NS", "TCS.NS", "HDFCBANK.NS", "INFY.NS", "HINDUNILVR.NS",
    "ICICIBANK.NS", "SBIN.NS", "BHARTIARTL.NS", "KOTAKBANK.NS", "ITC.NS",
    "LT.NS", "ASIANPAINT.NS", "AXISBANK.NS", "MARUTI.NS", "TITAN.NS",
    "NESTLEIND.NS", "HCLTECH.NS", "SUNPHARMA.NS", "BAJFINANCE.NS", "ULTRACEMCO.NS",
    "POWERGRID.NS", "TATAMOTORS.NS", "ONGC.NS", "WIPRO.NS", "NTPC.NS",
    "COALINDIA.NS", "JSWSTEEL.NS", "TATASTEEL.NS", "GRASIM.NS", "ADANIENT.NS",
    "HDFCLIFE.NS", "SBILIFE.NS", "BPCL.NS", "BAJAJFINSV.NS", "TECHM.NS",
    "EICHERMOT.NS", "HINDALCO.NS", "BRITANNIA.NS", "DIVISLAB.NS", "CIPLA.NS",
    "DRREDDY.NS", "APOLLOHOSP.NS", "HEROMOTOCO.NS", "BAJAJ-AUTO.NS", "TATACONSUM.NS",
    "ADANIPORTS.NS", "SHREECEM.NS", "INDUSINDBK.NS", "LTIM.NS", "SHRIRAMFIN.NS",
]

NIFTY_100_ADDITIONAL = [
    "AMBUJACEM.NS", "BANDHANBNK.NS", "BANKBARODA.NS", "BERGEPAINT.NS", "BIOCON.NS",
    "BOSCHLTD.NS", "CANBK.NS", "CHOLAFIN.NS", "COLPAL.NS", "DABUR.NS",
    "DALBHARAT.NS", "GODREJCP.NS", "HAVELLS.NS", "IDFCFIRSTB.NS", "INDIGO.NS",
    "IOC.NS", "IRCTC.NS", "JSWENERGY.NS", "LICI.NS", "LUPIN.NS",
    "M&M.NS", "MARICO.NS", "MOTHERSON.NS", "MPHASIS.NS", "MRF.NS",
    "MUTHOOTFIN.NS", "NAUKRI.NS", "NMDC.NS", "PERSISTENT.NS", "PIDILITIND.NS",
    "PIIND.NS", "PNB.NS", "RECLTD.NS", "SAIL.NS", "SIEMENS.NS",
    "SRF.NS", "TATAPOWER.NS", "TORNTPHARM.NS", "TRENT.NS", "TVSMOTOR.NS",
    "UBL.NS", "VEDL.NS", "VOLTAS.NS", "ZYDUSLIFE.NS", "DMART.NS",
    "DLF.NS", "PFC.NS", "HAL.NS", "BEL.NS", "ICICIPRULI.NS",
]

NIFTY_100 = NIFTY_50 + NIFTY_100_ADDITIONAL

ETF_UNIVERSE = [
    "NIFTYBEES.NS", "JUNIORBEES.NS", "GOLDBEES.NS", "SILVERBEES.NS",
    "CPSEETF.NS", "PSUBNKBEES.NS", "PHARMABEES.NS", "ITBEES.NS",
    "AUTOBEES.NS", "CONSUMBEES.NS", "DIVOPPBEES.NS", "BANKBEES.NS",
]

SECTOR_STOCKS = {
    "banking": ["HDFCBANK.NS", "ICICIBANK.NS", "SBIN.NS", "AXISBANK.NS",
                "KOTAKBANK.NS", "INDUSINDBK.NS", "BANKBARODA.NS", "PNB.NS",
                "CANBK.NS", "IDFCFIRSTB.NS", "FEDERALBNK.NS"],
    "it": ["TCS.NS", "INFY.NS", "HCLTECH.NS", "WIPRO.NS", "TECHM.NS",
           "LTIM.NS", "MPHASIS.NS", "PERSISTENT.NS", "COFORGE.NS"],
    "auto": ["MARUTI.NS", "TATAMOTORS.NS", "BAJAJ-AUTO.NS", "HEROMOTOCO.NS",
             "EICHERMOT.NS", "M&M.NS", "TVSMOTOR.NS", "MOTHERSON.NS", "BHARATFORG.NS"],
    "pharma": ["SUNPHARMA.NS", "DRREDDY.NS", "CIPLA.NS", "DIVISLAB.NS",
               "BIOCON.NS", "LUPIN.NS", "TORNTPHARM.NS", "AUROPHARMA.NS",
               "ALKEM.NS", "ZYDUSLIFE.NS"],
    "fmcg": ["HINDUNILVR.NS", "NESTLEIND.NS", "ITC.NS", "BRITANNIA.NS",
             "TATACONSUM.NS", "DABUR.NS", "MARICO.NS", "GODREJCP.NS", "COLPAL.NS"],
    "energy": ["RELIANCE.NS", "ONGC.NS", "BPCL.NS", "IOC.NS", "NTPC.NS",
               "POWERGRID.NS", "COALINDIA.NS", "GAIL.NS", "TATAPOWER.NS"],
    "metals": ["TATASTEEL.NS", "JSWSTEEL.NS", "HINDALCO.NS", "VEDL.NS",
               "SAIL.NS", "NMDC.NS", "JINDALSTEL.NS"],
    "financial": ["BAJFINANCE.NS", "BAJAJFINSV.NS", "HDFCLIFE.NS", "SBILIFE.NS",
                  "ICICIPRULI.NS", "LICI.NS", "CHOLAFIN.NS", "MUTHOOTFIN.NS",
                  "SHRIRAMFIN.NS", "RECLTD.NS", "PFC.NS"],
    "cement": ["ULTRACEMCO.NS", "SHREECEM.NS", "AMBUJACEM.NS", "DALBHARAT.NS"],
    "realty": ["DLF.NS", "DMART.NS", "TRENT.NS", "TITAN.NS"],
}


def get_universe(name: str) -> list[str]:
    name = name.lower()
    return {
        "nifty50": NIFTY_50,
        "nifty100": NIFTY_100,
        "etf": ETF_UNIVERSE,
    }.get(name, NIFTY_50).copy()


def get_sector(name: str) -> list[str]:
    return SECTOR_STOCKS.get(name.lower(), []).copy()
